---
# file: mariadb/tasks/main.yml

- name: Install mariadb packages
  dnf:
    pkg: "{{ item }}"
    state: "installed"
  with_items:
    - 'mariadb-server'
    - 'MySQL-python'
  tags:
    - 'packages'

- name: enable MariaDB server
  service:
    name: 'mariadb'
    enabled: yes
    state: 'started'
  tags:
    - 'service'

- name: set the root password.
  mysql_user:
    user: 'root'
    password: "{{ mysql_root_password }}"
    host: 'localhost'

- name: configure MySql for easy access as root user
  template:
    src: 'root_dot_my.cnf.j2'
    dest: '/root/.my.cnf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: remove anonymous MySQL server user for the hostname
  mysql_user:
    user: ""
    host: "{{ ansible_fqdn }}"
    state: "absent"

- name: delete the anonymous MySQL server user for localhost
  mysql_user:
    user: ""
    state: "absent"

- name: secure the MySQL root user for IPV6 localhost (::1)
  mysql_user:
    user: "root"
    password: "{{ mysql_root_password }}"
    host: "::1"

- name: secure the MySQL root user for IPV4 localhost (127.0.0.1)
  mysql_user:
    user: "root"
    password: "{{ mysql_root_password }}"
    host: "127.0.0.1"

- name: secure the MySQL root user for localhost domain (localhost)
  mysql_user:
    user: "root"
    password: "{{ mysql_root_password }}"
    host: "localhost"

- name: secure the MySQL root user for hostname
  mysql_user:
    user: "root"
    password: "{{ mysql_root_password }}"
    host: "{{ ansible_fqdn }}"

- name: remove the MySQL test database
  mysql_db:
    db: test
    state: absent
