---
# file: roles/spamassassin/handlers/main.yml

- name: run sa-compile
  action: shell /usr/bin/sa-compile
  ignore_errors: yes

- name: restart spamassassin
  service: name=spamassassin state=restarted