---
# file: roles/spamassassin/handlers/main.yml

- name: run sa-compile
  shell: '/usr/bin/sa-compile'
  ignore_errors: yes
  tags:
    - 'skip_ansible_lint'

- name: restart spamassassin
  service:
    name: 'spamassassin'
    state: 'restarted'
